import { useMemo } from 'react'
import { useParams } from 'react-router-dom'
import { motion } from 'framer-motion'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const DATA = {
  stardrift: { id: 'stardrift', title: 'Stardrift Over Neo‑Tokyo', genre: 'Sci‑Fi', date: '2025-07-14', tags: ['space','city','neon'], src: 'https://images.unsplash.com/photo-1747595062006-6cde8e2870f4?ixid=M3w3OTkxMTl8MHwxfHNlYXJjaHwxfHxTdGFyZHJpZnQlMjBPdmVyJTIwTmVvJUUyJTgwJTkxVG9reW98ZW58MHwwfHx8MTc2MjkyNTE2Nnww&ixlib=rb-4.1.0&w=1600&auto=format&fit=crop&q=80', banner: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600&auto=format&fit=crop', description: 'An astronaut glides above a neon city as ribbons of light weave between towers. Generated by diffusion + depth‑guided style transfer.' },
  aurora: { id: 'aurora', title: 'Aurora Shrine', genre: 'Fantasy', date: '2025-06-02', tags: ['forest','spirit','light'], src: 'https://images.unsplash.com/photo-1747595062006-6cde8e2870f4?ixid=M3w3OTkxMTl8MHwxfHNlYXJjaHwxfHxTdGFyZHJpZnQlMjBPdmVyJTIwTmVvJUUyJTgwJTkxVG9reW98ZW58MHwwfHx8MTc2MjkyNTE2Nnww&ixlib=rb-4.1.0&w=1600&auto=format&fit=crop&q=80', banner: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=1600&auto=format&fit=crop', description: 'A shrine bathed in aurora with luminous spirits drifting through the air. Built from text‑to‑video prompts + character control nets.' },
  kiss: { id: 'kiss', title: 'Skybound Promise', genre: 'Romance', date: '2025-05-10', tags: ['sky','clouds','dream'], src: 'https://images.unsplash.com/photo-1747595062006-6cde8e2870f4?ixid=M3w3OTkxMTl8MHwxfHNlYXJjaHwxfHxTdGFyZHJpZnQlMjBPdmVyJTIwTmVvJUUyJTgwJTkxVG9reW98ZW58MHwwfHx8MTc2MjkyNTE2Nnww&ixlib=rb-4.1.0&w=1600&auto=format&fit=crop&q=80', banner: 'https://images.unsplash.com/photo-1520971702667-3b1d7b27f5f7?q=80&w=1600&auto=format&fit=crop', description: 'Two souls meet above drifting clouds while time pauses around them. Dreamlike rendering via keyframe interpolation.' },
  mecha: { id: 'mecha', title: 'Mecha Alley', genre: 'Action', date: '2025-03-18', tags: ['mecha','rain','alley'], src: 'https://images.unsplash.com/photo-1747595062006-6cde8e2870f4?ixid=M3w3OTkxMTl8MHwxfHNlYXJjaHwxfHxTdGFyZHJpZnQlMjBPdmVyJTIwTmVvJUUyJTgwJTkxVG9reW98ZW58MHwwfHx8MTc2MjkyNTE2Nnww&ixlib=rb-4.1.0&w=1600&auto=format&fit=crop&q=80', banner: 'https://images.unsplash.com/photo-1520971702667-3b1d7b27f5f7?q=80&w=1600&auto=format&fit=crop', description: 'A towering mech awakens in a rain‑soaked alley, lights breathing to life. Composited from pose‑controlled video synthesis.' },
}

function JsonLd({ item }) {
  const data = {
    '@context': 'https://schema.org',
    '@type': 'CreativeWork',
    name: item.title,
    genre: item.genre,
    dateCreated: item.date,
    image: item.banner,
    video: {
      '@type': 'VideoObject',
      name: item.title,
      description: item.description,
      thumbnailUrl: item.banner,
      uploadDate: item.date,
      contentUrl: item.src,
      encodingFormat: 'video/webm'
    },
    keywords: item.tags.join(', '),
    description: item.description,
  }
  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }} />
}

export default function Detail() {
  const { id } = useParams()
  const item = useMemo(() => DATA[id], [id])

  if (!item) return (
    <main className="min-h-[100svh] grid place-items-center text-white bg-slate-950">
      <p>Not found.</p>
    </main>
  )

  return (
    <div className="min-h-[100svh] bg-slate-950 text-white">
      <Navbar />
      <main>
        <JsonLd item={item} />
        <section className="relative h-[50svh] overflow-hidden">
          <img src={item.banner} alt="banner" className="absolute inset-0 w-full h-full object-cover"/>
          <div className="absolute inset-0 bg-gradient-to-b from-slate-950/40 to-slate-950"></div>
          <div className="relative z-10 h-full flex items-end">
            <div className="mx-auto max-w-6xl px-6 pb-10">
              <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="text-3xl md:text-5xl font-bold drop-shadow">{item.title}</motion.h1>
              <p className="text-white/70 mt-2">{item.genre} • {item.date}</p>
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-6xl px-6 py-10 grid md:grid-cols-3 gap-8">
          <div className="md:col-span-2">
            <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-white/5 backdrop-blur">
              <video src={item.src} controls loop playsInline preload="metadata" className="w-full h-auto"></video>
            </div>
            <p className="mt-6 text-white/80 leading-relaxed">{item.description}</p>
          </div>
          <aside>
            <div className="rounded-2xl border border-white/10 bg-white/5 backdrop-blur p-4">
              <h3 className="font-semibold">Tags</h3>
              <div className="mt-2 flex flex-wrap gap-2">
                {item.tags.map(t => (
                  <span key={t} className="rounded-full px-3 py-1 text-xs bg-white/10 border border-white/10 text-white/80">{t}</span>
                ))}
              </div>
            </div>
            <div className="mt-6 rounded-2xl border border-white/10 bg-white/5 backdrop-blur p-4">
              <h3 className="font-semibold">Related</h3>
              <div className="mt-3 space-y-3">
                {Object.values(DATA).filter(d=>d.id!==item.id).slice(0,3).map(rel => (
                  <a key={rel.id} href={`/gallery/${rel.id}`} className="flex items-center gap-3 group">
                    <img src={rel.banner} alt={rel.title} className="w-20 h-14 object-cover rounded-lg border border-white/10"/>
                    <div>
                      <p className="text-sm text-white/90 group-hover:text-white">{rel.title}</p>
                      <p className="text-xs text-white/60">{rel.genre}</p>
                    </div>
                  </a>
                ))}
              </div>
            </div>
          </aside>
        </section>
      </main>
      <Footer />
    </div>
  )
}
